baseURL = "https://rickshf.github.io/"
languageCode = 'en-us'
title = 'rickshf'
disableKinds = ['taxonomy', 'term', 'section']

[markup]
  [markup.highlight]
      noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableGitInfo = true
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.pt]
    languageName = 'Português'
    weight = 2
