baseURL = "https://rickshf.github.io/"
defaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'rickshf'
disableKinds = ['taxonomy', 'term', 'section']

[markup]
  [markup.highlight]
      noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableGitInfo = true
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[languages.en]
  languageName = 'English'
  weight = 1

[languages.pt-br]
  languageName = 'Português (Brasil)'
  weight = 2
